name: CI - Test & Push to Official Main

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Set Environment Variables
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_USER=test" >> $GITHUB_ENV
          echo "DB_PASSWORD=test" >> $GITHUB_ENV
          echo "DB_NAME=test" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=dummy" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=dummy" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=dummy" >> $GITHUB_ENV
          echo "JWT_SECRET=secret" >> $GITHUB_ENV

      - name: Run Tests
        run: python -m pytest app/tests --maxfail=1 --disable-warnings -q

  push-to-official-main:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions CI"
          git config --global user.email "github-actions-ci[bot]@users.noreply.github.com"
          git remote add official_main git@github.com:EpitechPGE3-2025/G-SVR-500-PAR-5-1-survivor-6.git

      - name: Push to Official Main Repository
        run: |
          git fetch official_main
          git push official_main main --force
